# You must change these to your own details.
[package]
name = "wasm-game-prototype"
description = "A prototype of a simple rust-based MMO"
version = "0.1.0"
authors = ["reilemx@gmail.com"]
categories = ["wasm", "games"]
readme = "README.md"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[profile.release]
lto = true

[features]
default = ["wee_alloc"]

[dependencies]
# Bindings for JS & rust
wasm-bindgen = "0.2.45"
# Allocator, produces smaller wasm outputs
wee_alloc = { version = "0.4.2", optional = true }
# Cross platform game loop, uses web_sys request_animation_frame under the hood for wasm
game-loop = "0.9.1"

# web_sys imported with console
[dependencies.web-sys]
version = "0.3.22"
features = ["console"]

# `console_error_panic_hook` enabled only in debug
[target."cfg(debug_assertions)".dependencies]
console_error_panic_hook = "0.1.5"

# These crates are used for running unit tests.
[dev-dependencies]
wasm-bindgen-test = "0.2.45"
futures = "0.1.27"
js-sys = "0.3.22"
wasm-bindgen-futures = "0.3.22"
